### ISSUE TITLE
Fatal typo on line 27 of Lab1/Lab1Worksheet.tex

### ISSUE THREAD

**Issue by astern** [xandbox/xandbox#1]
### BUG
Currently, line 27 of Lab1/Lab1Worksheet.tex reads:

`Expressed to six decimal places, $\pi \appro \answer[tolerance=0.0000005]{3.141592653}$`

However, `\appro` (which is a typo of `\approx`) is not a valid LaTeX command and causes compilation to fail.

### PROPOSED SOLUTION
Fix the typo by changing the line to:

`Expressed to six decimal places, $\pi \approx \answer[tolerance=0.0000005]{3.141592653}$`

**Comment by kisonecat** [comment]
ae56eba91b345eb6cf79c910040fb8febcca2874 fixes this.
